# Generated by Django 3.1.5 on 2021-05-20 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dogbreed',
            fields=[
                ('dogbreed', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('home', models.TextField()),
                ('cellphone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mydog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogimage', models.ImageField(blank=True, upload_to='photo_%Y_%m_%d')),
                ('dogname', models.CharField(max_length=50)),
                ('dogage', models.IntegerField()),
                ('dogsex', models.CharField(max_length=50)),
                ('dogbreed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findog.dogbreed')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findog.member')),
            ],
        ),
        migrations.CreateModel(
            name='missingdog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('findplace', models.TextField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('cellphone', models.IntegerField()),
                ('explanation', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='photo_%Y_%m_%d')),
                ('findtime', models.DateTimeField()),
                ('dogbreed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findog.dogbreed')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findog.member')),
            ],
        ),
    ]
