# Generated by Django 3.1.5 on 2021-05-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dogcenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('cellphone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
