# Generated by Django 3.1.5 on 2021-05-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findog', '0003_uploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingdog',
            name='cellphone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='missingdog',
            name='findtime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='missingdog',
            name='lat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='missingdog',
            name='lon',
            field=models.CharField(max_length=50),
        ),
    ]
