# Generated by Django 3.1.5 on 2021-05-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findog', '0005_auto_20210525_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='findingdog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lostplace', models.CharField(max_length=100)),
                ('losttime', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=20)),
                ('explanation', models.TextField()),
                ('cellphone', models.CharField(max_length=20)),
                ('img', models.ImageField(blank=True, upload_to='photo_%Y_%m_%d')),
                ('delete', models.BooleanField(default=False)),
                ('dogbreed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findog.dogbreed')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findog.member')),
            ],
        ),
    ]
