# Generated by Django 3.1.5 on 2021-05-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findog', '0006_findingdog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingdog',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='missingdog',
            name='lon',
        ),
    ]
